use database ai_db;
use schema public;
use warehouse dbt_handson;

CREATE OR REPLACE SECURITY INTEGRATION WEBEX_OAUTH
TYPE = OAUTH
ENABLED = TRUE
OAUTH_CLIENT = CUSTOM
OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'

OAUTH_REDIRECT_URI = 'http://localhost:3000/callback'

OAUTH_ALLOW_NON_TLS_REDIRECT_URI = TRUE
OAUTH_ISSUE_REFRESH_TOKENS = TRUE
OAUTH_REFRESH_TOKEN_VALIDITY = 7776000
OAUTH_ENFORCE_PKCE = TRUE;


DESC SECURITY INTEGRATION WEBEX_OAUTH;

-- Run this to get the Client Secret (save the value for 00.js → SNOWFLAKE_CLIENT_SECRET)
SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('WEBEX_OAUTH');